name = "d1studio"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "cd ../web && npm run build"

[site]
bucket = "../web/dist"

[[d1_databases]]
binding = "APP_DB"
database_name = "${APP_DB_NAME}"
database_id = "${APP_DB_ID}"

[[d1_databases]]
binding = "DB_SLOT_1"
database_name = "${DB_SLOT_1_NAME}"
database_id = "${DB_SLOT_1_ID}"
