name = "d1studio"
main = "src/server/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./dist"

[[d1_databases]]
binding = "APP_DB"
database_name = "${APP_DB_NAME}"
database_id = "${APP_DB_ID}"

[[d1_databases]]
binding = "DB_SLOT_1"
database_name = "${DB_SLOT_1_NAME}"
database_id = "${DB_SLOT_1_ID}"

[[d1_databases]]
binding = "DB_SLOT_2"
database_name = "${DB_SLOT_2_NAME}"
database_id = "${DB_SLOT_2_ID}"

[[d1_databases]]
binding = "DB_SLOT_3"
database_name = "${DB_SLOT_3_NAME}"
database_id = "${DB_SLOT_3_ID}"

[[d1_databases]]
binding = "DB_SLOT_4"
database_name = "${DB_SLOT_4_NAME}"
database_id = "${DB_SLOT_4_ID}"

[[d1_databases]]
binding = "DB_SLOT_5"
database_name = "${DB_SLOT_5_NAME}"
database_id = "${DB_SLOT_5_ID}"

[[d1_databases]]
binding = "DB_SLOT_6"
database_name = "${DB_SLOT_6_NAME}"
database_id = "${DB_SLOT_6_ID}"

[[d1_databases]]
binding = "DB_SLOT_7"
database_name = "${DB_SLOT_7_NAME}"
database_id = "${DB_SLOT_7_ID}"

[[d1_databases]]
binding = "DB_SLOT_8"
database_name = "${DB_SLOT_8_NAME}"
database_id = "${DB_SLOT_8_ID}"

[[d1_databases]]
binding = "DB_SLOT_9"
database_name = "${DB_SLOT_9_NAME}"
database_id = "${DB_SLOT_9_ID}"

[[d1_databases]]
binding = "DB_SLOT_10"
database_name = "${DB_SLOT_10_NAME}"
database_id = "${DB_SLOT_10_ID}"
